# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/DELL/Desktop/TKF_FIRMWARE/TKF_new_9.30/tkf_test_1/tkf_test_1.srcs/sources_1/ip/ram_32_16384/ram_32_16384.xci
# IP: The module: 'ram_32_16384' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/TKF_FIRMWARE/TKF_new_9.30/tkf_test_1/tkf_test_1.srcs/sources_1/ip/ram_32_16384/ram_32_16384_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_32_16384'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/DELL/Desktop/TKF_FIRMWARE/TKF_new_9.30/tkf_test_1/tkf_test_1.srcs/sources_1/ip/ram_32_16384/ram_32_16384.xci
# IP: The module: 'ram_32_16384' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/TKF_FIRMWARE/TKF_new_9.30/tkf_test_1/tkf_test_1.srcs/sources_1/ip/ram_32_16384/ram_32_16384_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_32_16384'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
